

pipeline {
    agent any
    stages {
        stage('Build') { 
        steps {
               bat '''
               cd BackEnd
               mvn -B -DskipTests clean package
               '''
            }
        }
         stage('Test') { 
            steps {
                bat'''
               cd BackEnd 
                mvn test
               '''  
            }
            }
            
            
        stage('Deliver') {
            steps {
            
            bat '''
            cd BackEnd/target     
           java -jar LegacyProject-0.0.1-SNAPSHOT.jar
            '''
            
               
                
            }
        }    
            
        
    }
}